package io.github.kitectlab.winrt.projections.support

// Deterministic generator handoff for .cswinrt WinRTGenericAbiRegistry writer parity.

internal data class GenericAbiDelegateEntry(
    val name: String,
    val sourceGenericType: String,
    val operation: String,
    val declaration: String,
    val abiParameterTypes: List<String>,
    val typeArrayShape: List<String>,
)

internal object WinRTGenericAbiRegistry {
    val DERIVED_GENERIC_INTERFACES: List<String> = listOf("Windows.Foundation.Collections.IMap", "Windows.Foundation.Collections.IMapView", "Windows.Foundation.Collections.IObservableMap", "Windows.Foundation.Collections.IObservableVector", "Windows.Foundation.Collections.IPropertySet", "Windows.Foundation.Collections.IVector", "Windows.Foundation.Collections.IVectorView")
    val GENERIC_ABI_DELEGATES: List<GenericAbiDelegateEntry> = listOf(
        GenericAbiDelegateEntry(
            name = "_append_Boolean",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Boolean>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Boolean(void*, Boolean);",
            abiParameterTypes = listOf("void*", "Boolean", "int"),
            typeArrayShape = listOf("void*", "Boolean", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Boolean",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Boolean>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Boolean(void*, out Boolean);",
            abiParameterTypes = listOf("void*", "out Boolean", "int"),
            typeArrayShape = listOf("void*", "Boolean.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Boolean",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Boolean>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Boolean(void*, uint, out Boolean);",
            abiParameterTypes = listOf("void*", "uint", "out Boolean", "int"),
            typeArrayShape = listOf("void*", "uint", "Boolean.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Boolean",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Boolean>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Boolean(void*, Boolean, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Boolean", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Boolean", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Boolean",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Boolean>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Boolean(void*, uint, Boolean);",
            abiParameterTypes = listOf("void*", "uint", "Boolean", "int"),
            typeArrayShape = listOf("void*", "uint", "Boolean", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Char",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Char>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Char(void*, Char);",
            abiParameterTypes = listOf("void*", "Char", "int"),
            typeArrayShape = listOf("void*", "Char", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Char",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Char>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Char(void*, out Char);",
            abiParameterTypes = listOf("void*", "out Char", "int"),
            typeArrayShape = listOf("void*", "Char.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Char",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Char>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Char(void*, uint, out Char);",
            abiParameterTypes = listOf("void*", "uint", "out Char", "int"),
            typeArrayShape = listOf("void*", "uint", "Char.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Char",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Char>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Char(void*, Char, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Char", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Char", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Char",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Char>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Char(void*, uint, Char);",
            abiParameterTypes = listOf("void*", "uint", "Char", "int"),
            typeArrayShape = listOf("void*", "uint", "Char", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Double",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Double>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Double(void*, Double);",
            abiParameterTypes = listOf("void*", "Double", "int"),
            typeArrayShape = listOf("void*", "Double", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Double",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Double>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Double(void*, out Double);",
            abiParameterTypes = listOf("void*", "out Double", "int"),
            typeArrayShape = listOf("void*", "Double.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Double",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Double>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Double(void*, uint, out Double);",
            abiParameterTypes = listOf("void*", "uint", "out Double", "int"),
            typeArrayShape = listOf("void*", "uint", "Double.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Double",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Double>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Double(void*, Double, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Double", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Double", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Double",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Double>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Double(void*, uint, Double);",
            abiParameterTypes = listOf("void*", "uint", "Double", "int"),
            typeArrayShape = listOf("void*", "uint", "Double", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Float",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Float>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Float(void*, Float);",
            abiParameterTypes = listOf("void*", "Float", "int"),
            typeArrayShape = listOf("void*", "Float", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Float",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Float>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Float(void*, out Float);",
            abiParameterTypes = listOf("void*", "out Float", "int"),
            typeArrayShape = listOf("void*", "Float.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Float",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Float>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Float(void*, uint, out Float);",
            abiParameterTypes = listOf("void*", "uint", "out Float", "int"),
            typeArrayShape = listOf("void*", "uint", "Float.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Float",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Float>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Float(void*, Float, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Float", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Float", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Float",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Float>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Float(void*, uint, Float);",
            abiParameterTypes = listOf("void*", "uint", "Float", "int"),
            typeArrayShape = listOf("void*", "uint", "Float", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Int",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Int>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Int(void*, Int);",
            abiParameterTypes = listOf("void*", "Int", "int"),
            typeArrayShape = listOf("void*", "Int", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Int",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Int>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Int(void*, out Int);",
            abiParameterTypes = listOf("void*", "out Int", "int"),
            typeArrayShape = listOf("void*", "Int.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Int",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Int>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Int(void*, uint, out Int);",
            abiParameterTypes = listOf("void*", "uint", "out Int", "int"),
            typeArrayShape = listOf("void*", "uint", "Int.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Int",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Int>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Int(void*, Int, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Int", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Int", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Int",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Int>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Int(void*, uint, Int);",
            abiParameterTypes = listOf("void*", "uint", "Int", "int"),
            typeArrayShape = listOf("void*", "uint", "Int", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Long",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Long>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Long(void*, Long);",
            abiParameterTypes = listOf("void*", "Long", "int"),
            typeArrayShape = listOf("void*", "Long", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Long",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Long>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Long(void*, out Long);",
            abiParameterTypes = listOf("void*", "out Long", "int"),
            typeArrayShape = listOf("void*", "Long.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Long",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Long>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Long(void*, uint, out Long);",
            abiParameterTypes = listOf("void*", "uint", "out Long", "int"),
            typeArrayShape = listOf("void*", "uint", "Long.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Long",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Long>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Long(void*, Long, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Long", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Long", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Long",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Long>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Long(void*, uint, Long);",
            abiParameterTypes = listOf("void*", "uint", "Long", "int"),
            typeArrayShape = listOf("void*", "uint", "Long", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Short",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Short>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Short(void*, Short);",
            abiParameterTypes = listOf("void*", "Short", "int"),
            typeArrayShape = listOf("void*", "Short", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Short",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Short>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Short(void*, out Short);",
            abiParameterTypes = listOf("void*", "out Short", "int"),
            typeArrayShape = listOf("void*", "Short.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Short",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Short>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Short(void*, uint, out Short);",
            abiParameterTypes = listOf("void*", "uint", "out Short", "int"),
            typeArrayShape = listOf("void*", "uint", "Short.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Short",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Short>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Short(void*, Short, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Short", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Short", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Short",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Short>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Short(void*, uint, Short);",
            abiParameterTypes = listOf("void*", "uint", "Short", "int"),
            typeArrayShape = listOf("void*", "uint", "Short", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_System_Guid",
            sourceGenericType = "Windows.Foundation.Collections.IVector<System.Guid>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_System_Guid(void*, System.Guid);",
            abiParameterTypes = listOf("void*", "System.Guid", "int"),
            typeArrayShape = listOf("void*", "System.Guid", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_System_Guid",
            sourceGenericType = "Windows.Foundation.Collections.IVector<System.Guid>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_System_Guid(void*, out System.Guid);",
            abiParameterTypes = listOf("void*", "out System.Guid", "int"),
            typeArrayShape = listOf("void*", "System.Guid.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_System_Guid",
            sourceGenericType = "Windows.Foundation.Collections.IVector<System.Guid>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_System_Guid(void*, uint, out System.Guid);",
            abiParameterTypes = listOf("void*", "uint", "out System.Guid", "int"),
            typeArrayShape = listOf("void*", "uint", "System.Guid.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_System_Guid",
            sourceGenericType = "Windows.Foundation.Collections.IVector<System.Guid>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_System_Guid(void*, System.Guid, out uint, out byte);",
            abiParameterTypes = listOf("void*", "System.Guid", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "System.Guid", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_System_Guid",
            sourceGenericType = "Windows.Foundation.Collections.IVector<System.Guid>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_System_Guid(void*, uint, System.Guid);",
            abiParameterTypes = listOf("void*", "uint", "System.Guid", "int"),
            typeArrayShape = listOf("void*", "uint", "System.Guid", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_UByte",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UByte>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_UByte(void*, UByte);",
            abiParameterTypes = listOf("void*", "UByte", "int"),
            typeArrayShape = listOf("void*", "UByte", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_UByte",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UByte>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_UByte(void*, out UByte);",
            abiParameterTypes = listOf("void*", "out UByte", "int"),
            typeArrayShape = listOf("void*", "UByte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_UByte",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UByte>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_UByte(void*, uint, out UByte);",
            abiParameterTypes = listOf("void*", "uint", "out UByte", "int"),
            typeArrayShape = listOf("void*", "uint", "UByte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_UByte",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UByte>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_UByte(void*, UByte, out uint, out byte);",
            abiParameterTypes = listOf("void*", "UByte", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "UByte", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_UByte",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UByte>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_UByte(void*, uint, UByte);",
            abiParameterTypes = listOf("void*", "uint", "UByte", "int"),
            typeArrayShape = listOf("void*", "uint", "UByte", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_UInt",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UInt>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_UInt(void*, UInt);",
            abiParameterTypes = listOf("void*", "UInt", "int"),
            typeArrayShape = listOf("void*", "UInt", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_UInt",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UInt>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_UInt(void*, out UInt);",
            abiParameterTypes = listOf("void*", "out UInt", "int"),
            typeArrayShape = listOf("void*", "UInt.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_UInt",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UInt>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_UInt(void*, uint, out UInt);",
            abiParameterTypes = listOf("void*", "uint", "out UInt", "int"),
            typeArrayShape = listOf("void*", "uint", "UInt.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_UInt",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UInt>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_UInt(void*, UInt, out uint, out byte);",
            abiParameterTypes = listOf("void*", "UInt", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "UInt", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_UInt",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UInt>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_UInt(void*, uint, UInt);",
            abiParameterTypes = listOf("void*", "uint", "UInt", "int"),
            typeArrayShape = listOf("void*", "uint", "UInt", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_ULong",
            sourceGenericType = "Windows.Foundation.Collections.IVector<ULong>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_ULong(void*, ULong);",
            abiParameterTypes = listOf("void*", "ULong", "int"),
            typeArrayShape = listOf("void*", "ULong", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_ULong",
            sourceGenericType = "Windows.Foundation.Collections.IVector<ULong>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_ULong(void*, out ULong);",
            abiParameterTypes = listOf("void*", "out ULong", "int"),
            typeArrayShape = listOf("void*", "ULong.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_ULong",
            sourceGenericType = "Windows.Foundation.Collections.IVector<ULong>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_ULong(void*, uint, out ULong);",
            abiParameterTypes = listOf("void*", "uint", "out ULong", "int"),
            typeArrayShape = listOf("void*", "uint", "ULong.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_ULong",
            sourceGenericType = "Windows.Foundation.Collections.IVector<ULong>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_ULong(void*, ULong, out uint, out byte);",
            abiParameterTypes = listOf("void*", "ULong", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "ULong", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_ULong",
            sourceGenericType = "Windows.Foundation.Collections.IVector<ULong>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_ULong(void*, uint, ULong);",
            abiParameterTypes = listOf("void*", "uint", "ULong", "int"),
            typeArrayShape = listOf("void*", "uint", "ULong", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_UShort",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UShort>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_UShort(void*, UShort);",
            abiParameterTypes = listOf("void*", "UShort", "int"),
            typeArrayShape = listOf("void*", "UShort", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_UShort",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UShort>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_UShort(void*, out UShort);",
            abiParameterTypes = listOf("void*", "out UShort", "int"),
            typeArrayShape = listOf("void*", "UShort.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_UShort",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UShort>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_UShort(void*, uint, out UShort);",
            abiParameterTypes = listOf("void*", "uint", "out UShort", "int"),
            typeArrayShape = listOf("void*", "uint", "UShort.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_UShort",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UShort>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_UShort(void*, UShort, out uint, out byte);",
            abiParameterTypes = listOf("void*", "UShort", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "UShort", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_UShort",
            sourceGenericType = "Windows.Foundation.Collections.IVector<UShort>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_UShort(void*, uint, UShort);",
            abiParameterTypes = listOf("void*", "uint", "UShort", "int"),
            typeArrayShape = listOf("void*", "uint", "UShort", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Windows_Foundation_DateTime",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.DateTime>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Windows_Foundation_DateTime(void*, Windows.Foundation.DateTime);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.DateTime", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.DateTime", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Windows_Foundation_DateTime",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.DateTime>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Windows_Foundation_DateTime(void*, out Windows.Foundation.DateTime);",
            abiParameterTypes = listOf("void*", "out Windows.Foundation.DateTime", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.DateTime.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Windows_Foundation_DateTime",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.DateTime>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Windows_Foundation_DateTime(void*, uint, out Windows.Foundation.DateTime);",
            abiParameterTypes = listOf("void*", "uint", "out Windows.Foundation.DateTime", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.DateTime.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Windows_Foundation_DateTime",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.DateTime>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Windows_Foundation_DateTime(void*, Windows.Foundation.DateTime, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.DateTime", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.DateTime", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Windows_Foundation_DateTime",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.DateTime>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Windows_Foundation_DateTime(void*, uint, Windows.Foundation.DateTime);",
            abiParameterTypes = listOf("void*", "uint", "Windows.Foundation.DateTime", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.DateTime", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Windows_Foundation_Point",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Point>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Windows_Foundation_Point(void*, Windows.Foundation.Point);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.Point", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Point", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Windows_Foundation_Point",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Point>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Windows_Foundation_Point(void*, out Windows.Foundation.Point);",
            abiParameterTypes = listOf("void*", "out Windows.Foundation.Point", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Point.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Windows_Foundation_Point",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Point>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Windows_Foundation_Point(void*, uint, out Windows.Foundation.Point);",
            abiParameterTypes = listOf("void*", "uint", "out Windows.Foundation.Point", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.Point.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Windows_Foundation_Point",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Point>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Windows_Foundation_Point(void*, Windows.Foundation.Point, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.Point", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Point", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Windows_Foundation_Point",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Point>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Windows_Foundation_Point(void*, uint, Windows.Foundation.Point);",
            abiParameterTypes = listOf("void*", "uint", "Windows.Foundation.Point", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.Point", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Windows_Foundation_Rect",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Rect>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Windows_Foundation_Rect(void*, Windows.Foundation.Rect);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.Rect", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Rect", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Windows_Foundation_Rect",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Rect>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Windows_Foundation_Rect(void*, out Windows.Foundation.Rect);",
            abiParameterTypes = listOf("void*", "out Windows.Foundation.Rect", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Rect.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Windows_Foundation_Rect",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Rect>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Windows_Foundation_Rect(void*, uint, out Windows.Foundation.Rect);",
            abiParameterTypes = listOf("void*", "uint", "out Windows.Foundation.Rect", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.Rect.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Windows_Foundation_Rect",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Rect>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Windows_Foundation_Rect(void*, Windows.Foundation.Rect, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.Rect", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Rect", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Windows_Foundation_Rect",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Rect>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Windows_Foundation_Rect(void*, uint, Windows.Foundation.Rect);",
            abiParameterTypes = listOf("void*", "uint", "Windows.Foundation.Rect", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.Rect", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Windows_Foundation_Size",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Size>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Windows_Foundation_Size(void*, Windows.Foundation.Size);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.Size", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Size", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Windows_Foundation_Size",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Size>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Windows_Foundation_Size(void*, out Windows.Foundation.Size);",
            abiParameterTypes = listOf("void*", "out Windows.Foundation.Size", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Size.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Windows_Foundation_Size",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Size>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Windows_Foundation_Size(void*, uint, out Windows.Foundation.Size);",
            abiParameterTypes = listOf("void*", "uint", "out Windows.Foundation.Size", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.Size.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Windows_Foundation_Size",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Size>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Windows_Foundation_Size(void*, Windows.Foundation.Size, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.Size", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.Size", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Windows_Foundation_Size",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.Size>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Windows_Foundation_Size(void*, uint, Windows.Foundation.Size);",
            abiParameterTypes = listOf("void*", "uint", "Windows.Foundation.Size", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.Size", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_append_Windows_Foundation_TimeSpan",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.TimeSpan>",
            operation = "append",
            declaration = "internal unsafe delegate int _append_Windows_Foundation_TimeSpan(void*, Windows.Foundation.TimeSpan);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.TimeSpan", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.TimeSpan", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_Current_Windows_Foundation_TimeSpan",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.TimeSpan>",
            operation = "get_Current",
            declaration = "internal unsafe delegate int _get_Current_Windows_Foundation_TimeSpan(void*, out Windows.Foundation.TimeSpan);",
            abiParameterTypes = listOf("void*", "out Windows.Foundation.TimeSpan", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.TimeSpan.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_get_at_Windows_Foundation_TimeSpan",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.TimeSpan>",
            operation = "get_at",
            declaration = "internal unsafe delegate int _get_at_Windows_Foundation_TimeSpan(void*, uint, out Windows.Foundation.TimeSpan);",
            abiParameterTypes = listOf("void*", "uint", "out Windows.Foundation.TimeSpan", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.TimeSpan.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_index_of_Windows_Foundation_TimeSpan",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.TimeSpan>",
            operation = "index_of",
            declaration = "internal unsafe delegate int _index_of_Windows_Foundation_TimeSpan(void*, Windows.Foundation.TimeSpan, out uint, out byte);",
            abiParameterTypes = listOf("void*", "Windows.Foundation.TimeSpan", "out uint", "out byte", "int"),
            typeArrayShape = listOf("void*", "Windows.Foundation.TimeSpan", "uint.MakeByRefType()", "byte.MakeByRefType()", "int"),
        ),
        GenericAbiDelegateEntry(
            name = "_set_at_Windows_Foundation_TimeSpan",
            sourceGenericType = "Windows.Foundation.Collections.IVector<Windows.Foundation.TimeSpan>",
            operation = "set_at",
            declaration = "internal unsafe delegate int _set_at_Windows_Foundation_TimeSpan(void*, uint, Windows.Foundation.TimeSpan);",
            abiParameterTypes = listOf("void*", "uint", "Windows.Foundation.TimeSpan", "int"),
            typeArrayShape = listOf("void*", "uint", "Windows.Foundation.TimeSpan", "int"),
        ),
    )
    val DELEGATES_BY_NAME: Map<String, GenericAbiDelegateEntry> = GENERIC_ABI_DELEGATES.associateBy { it.name }
    val DELEGATES_BY_SOURCE_TYPE: Map<String, List<GenericAbiDelegateEntry>> = GENERIC_ABI_DELEGATES.groupBy { it.sourceGenericType }
    val DERIVED_GENERIC_INTERFACE_SET: Set<String> = DERIVED_GENERIC_INTERFACES.toSet()

    fun delegateNamed(name: String): GenericAbiDelegateEntry? = DELEGATES_BY_NAME[name]

    fun delegatesForSourceType(sourceGenericType: String): List<GenericAbiDelegateEntry> =
        DELEGATES_BY_SOURCE_TYPE[sourceGenericType].orEmpty()

    fun isDerivedGenericInterface(typeName: String): Boolean =
        typeName in DERIVED_GENERIC_INTERFACE_SET

    fun registerAbiDelegates(register: (typeArrayShape: List<String>, delegateName: String) -> Unit) {
        GENERIC_ABI_DELEGATES.forEach { entry ->
            register(entry.typeArrayShape, entry.name)
        }
    }
}
