package io.github.kitectlab.winrt.projections.support

// Deterministic generator handoff for .cswinrt WinRTAbiImplementationPlan writer parity.

internal data class AbiImplementationEntry(
    val typeName: String,
    val writesAbi: Boolean,
    val writesImplementationClass: Boolean,
    val vtableSlots: List<String>,
    val genericInvokeSlots: List<String>,
    val requiredInterfaces: List<String>,
    val explicitForwards: List<String>,
)

internal object WinRTAbiImplementationPlan {
    val ENTRIES: List<AbiImplementationEntry> = listOf(
        AbiImplementationEntry(
            typeName = "Windows.Foundation.AsyncActionCompletedHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.AsyncActionProgressHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.AsyncActionWithProgressCompletedHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.AsyncOperationCompletedHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.AsyncOperationProgressHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.AsyncOperationWithProgressCompletedHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IIterable",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("FIRST_SLOT"),
            genericInvokeSlots = listOf("First_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IIterator",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CURRENT_GETTER_SLOT", "HASCURRENT_GETTER_SLOT", "MOVENEXT_SLOT", "GETMANY_SLOT"),
            genericInvokeSlots = listOf("MoveNext_0", "GetMany_1"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IKeyValuePair",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("KEY_GETTER_SLOT", "VALUE_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IMap",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = listOf("LOOKUP_SLOT", "SIZE_GETTER_SLOT", "HASKEY_SLOT", "GETVIEW_SLOT", "INSERT_SLOT", "REMOVE_SLOT", "CLEAR_SLOT"),
            genericInvokeSlots = listOf("Lookup_0", "HasKey_2", "GetView_3", "Insert_4", "Remove_5", "Clear_6"),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<T0, T1>>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IMapChangedEventArgs",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("COLLECTIONCHANGE_GETTER_SLOT", "KEY_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IMapView",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = listOf("LOOKUP_SLOT", "SIZE_GETTER_SLOT", "HASKEY_SLOT", "SPLIT_SLOT"),
            genericInvokeSlots = listOf("Lookup_0", "HasKey_2", "Split_3"),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<T0, T1>>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IObservableMap",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = listOf("MAPCHANGED_ADD_SLOT", "MAPCHANGED_REMOVE_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IMap<T0, T1>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IObservableVector",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = listOf("VECTORCHANGED_ADD_SLOT", "VECTORCHANGED_REMOVE_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IVector<T0>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IPropertySet",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, System.Object>>", "Windows.Foundation.Collections.IMap<String, System.Object>", "Windows.Foundation.Collections.IObservableMap<String, System.Object>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IVector",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = listOf("GETAT_SLOT", "SIZE_GETTER_SLOT", "GETVIEW_SLOT", "INDEXOF_SLOT", "SETAT_SLOT", "INSERTAT_SLOT", "REMOVEAT_SLOT", "APPEND_SLOT", "REMOVEATEND_SLOT", "CLEAR_SLOT", "GETMANY_SLOT", "REPLACEALL_SLOT"),
            genericInvokeSlots = listOf("GetAt_0", "GetView_2", "IndexOf_3", "SetAt_4", "InsertAt_5", "RemoveAt_6", "Append_7", "RemoveAtEnd_8", "Clear_9", "GetMany_10", "ReplaceAll_11"),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<T0>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IVectorChangedEventArgs",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("COLLECTIONCHANGE_GETTER_SLOT", "INDEX_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.IVectorView",
            writesAbi = true,
            writesImplementationClass = true,
            vtableSlots = listOf("GETAT_SLOT", "SIZE_GETTER_SLOT", "INDEXOF_SLOT", "GETMANY_SLOT"),
            genericInvokeSlots = listOf("GetAt_0", "IndexOf_2", "GetMany_3"),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<T0>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.MapChangedEventHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.PropertySet",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, System.Object>>", "Windows.Foundation.Collections.IMap<String, System.Object>", "Windows.Foundation.Collections.IObservableMap<String, System.Object>", "Windows.Foundation.Collections.IPropertySet"),
            explicitForwards = listOf("Clear", "First", "GetView", "HasKey", "Insert", "Lookup", "Remove", "add_MapChanged", "get_Size", "remove_MapChanged"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.StringMap",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, String>>", "Windows.Foundation.Collections.IMap<String, String>", "Windows.Foundation.Collections.IObservableMap<String, String>"),
            explicitForwards = listOf("Clear", "First", "GetView", "HasKey", "Insert", "Lookup", "Remove", "add_MapChanged", "get_Size", "remove_MapChanged"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.ValueSet",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<String, System.Object>>", "Windows.Foundation.Collections.IMap<String, System.Object>", "Windows.Foundation.Collections.IObservableMap<String, System.Object>", "Windows.Foundation.Collections.IPropertySet"),
            explicitForwards = listOf("Clear", "First", "GetView", "HasKey", "Insert", "Lookup", "Remove", "add_MapChanged", "get_Size", "remove_MapChanged"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Collections.VectorChangedEventHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.DateTime",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Deferral",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IClosable", "Windows.Foundation.IDeferral"),
            explicitForwards = listOf("Close", "Complete"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.DeferralCompletedHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.EventHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.EventRegistrationToken",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.FoundationContract",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.GuidHelper",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.HResult",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IAsyncAction",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("COMPLETED_SETTER_SLOT", "COMPLETED_GETTER_SLOT", "GETRESULTS_SLOT"),
            genericInvokeSlots = listOf("GetResults_0"),
            requiredInterfaces = listOf("Windows.Foundation.IAsyncInfo"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IAsyncActionWithProgress",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("PROGRESS_SETTER_SLOT", "PROGRESS_GETTER_SLOT", "COMPLETED_SETTER_SLOT", "COMPLETED_GETTER_SLOT", "GETRESULTS_SLOT"),
            genericInvokeSlots = listOf("GetResults_0"),
            requiredInterfaces = listOf("Windows.Foundation.IAsyncInfo"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IAsyncInfo",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("ID_GETTER_SLOT", "STATUS_GETTER_SLOT", "ERRORCODE_GETTER_SLOT", "CANCEL_SLOT", "CLOSE_SLOT"),
            genericInvokeSlots = listOf("Cancel_0", "Close_1"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IAsyncOperation",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("COMPLETED_SETTER_SLOT", "COMPLETED_GETTER_SLOT", "GETRESULTS_SLOT"),
            genericInvokeSlots = listOf("GetResults_0"),
            requiredInterfaces = listOf("Windows.Foundation.IAsyncInfo"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IAsyncOperationWithProgress",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("PROGRESS_SETTER_SLOT", "PROGRESS_GETTER_SLOT", "COMPLETED_SETTER_SLOT", "COMPLETED_GETTER_SLOT", "GETRESULTS_SLOT"),
            genericInvokeSlots = listOf("GetResults_0"),
            requiredInterfaces = listOf("Windows.Foundation.IAsyncInfo"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IClosable",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CLOSE_SLOT"),
            genericInvokeSlots = listOf("Close_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IDeferral",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("COMPLETE_SLOT"),
            genericInvokeSlots = listOf("Complete_0"),
            requiredInterfaces = listOf("Windows.Foundation.IClosable"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IDeferralFactory",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATE_SLOT"),
            genericInvokeSlots = listOf("Create_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IGetActivationFactory",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("GETACTIVATIONFACTORY_SLOT"),
            genericInvokeSlots = listOf("GetActivationFactory_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IGuidHelperStatics",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATENEWGUID_SLOT", "EMPTY_GETTER_SLOT", "EQUALS_SLOT"),
            genericInvokeSlots = listOf("CreateNewGuid_0", "Equals_2"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IMemoryBuffer",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATEREFERENCE_SLOT"),
            genericInvokeSlots = listOf("CreateReference_0"),
            requiredInterfaces = listOf("Windows.Foundation.IClosable"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IMemoryBufferFactory",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATE_SLOT"),
            genericInvokeSlots = listOf("Create_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IMemoryBufferReference",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CAPACITY_GETTER_SLOT", "CLOSED_ADD_SLOT", "CLOSED_REMOVE_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IClosable"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IPropertyValue",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("TYPE_GETTER_SLOT", "ISNUMERICSCALAR_GETTER_SLOT", "GETUINT8_SLOT", "GETINT16_SLOT", "GETUINT16_SLOT", "GETINT32_SLOT", "GETUINT32_SLOT", "GETINT64_SLOT", "GETUINT64_SLOT", "GETSINGLE_SLOT", "GETDOUBLE_SLOT", "GETCHAR16_SLOT", "GETBOOLEAN_SLOT", "GETSTRING_SLOT", "GETGUID_SLOT", "GETDATETIME_SLOT", "GETTIMESPAN_SLOT", "GETPOINT_SLOT", "GETSIZE_SLOT", "GETRECT_SLOT", "GETUINT8ARRAY_SLOT", "GETINT16ARRAY_SLOT", "GETUINT16ARRAY_SLOT", "GETINT32ARRAY_SLOT", "GETUINT32ARRAY_SLOT", "GETINT64ARRAY_SLOT", "GETUINT64ARRAY_SLOT", "GETSINGLEARRAY_SLOT", "GETDOUBLEARRAY_SLOT", "GETCHAR16ARRAY_SLOT", "GETBOOLEANARRAY_SLOT", "GETSTRINGARRAY_SLOT", "GETINSPECTABLEARRAY_SLOT", "GETGUIDARRAY_SLOT", "GETDATETIMEARRAY_SLOT", "GETTIMESPANARRAY_SLOT", "GETPOINTARRAY_SLOT", "GETSIZEARRAY_SLOT", "GETRECTARRAY_SLOT"),
            genericInvokeSlots = listOf("GetUInt8_0", "GetInt16_1", "GetUInt16_2", "GetInt32_3", "GetUInt32_4", "GetInt64_5", "GetUInt64_6", "GetSingle_7", "GetDouble_8", "GetChar16_9", "GetBoolean_10", "GetString_11", "GetGuid_12", "GetDateTime_13", "GetTimeSpan_14", "GetPoint_15", "GetSize_16", "GetRect_17", "GetUInt8Array_18", "GetInt16Array_19", "GetUInt16Array_20", "GetInt32Array_21", "GetUInt32Array_22", "GetInt64Array_23", "GetUInt64Array_24", "GetSingleArray_25", "GetDoubleArray_26", "GetChar16Array_27", "GetBooleanArray_28", "GetStringArray_29", "GetInspectableArray_30", "GetGuidArray_31", "GetDateTimeArray_32", "GetTimeSpanArray_33", "GetPointArray_34", "GetSizeArray_35", "GetRectArray_36"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IPropertyValueStatics",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATEEMPTY_SLOT", "CREATEUINT8_SLOT", "CREATEINT16_SLOT", "CREATEUINT16_SLOT", "CREATEINT32_SLOT", "CREATEUINT32_SLOT", "CREATEINT64_SLOT", "CREATEUINT64_SLOT", "CREATESINGLE_SLOT", "CREATEDOUBLE_SLOT", "CREATECHAR16_SLOT", "CREATEBOOLEAN_SLOT", "CREATESTRING_SLOT", "CREATEINSPECTABLE_SLOT", "CREATEGUID_SLOT", "CREATEDATETIME_SLOT", "CREATETIMESPAN_SLOT", "CREATEPOINT_SLOT", "CREATESIZE_SLOT", "CREATERECT_SLOT", "CREATEUINT8ARRAY_SLOT", "CREATEINT16ARRAY_SLOT", "CREATEUINT16ARRAY_SLOT", "CREATEINT32ARRAY_SLOT", "CREATEUINT32ARRAY_SLOT", "CREATEINT64ARRAY_SLOT", "CREATEUINT64ARRAY_SLOT", "CREATESINGLEARRAY_SLOT", "CREATEDOUBLEARRAY_SLOT", "CREATECHAR16ARRAY_SLOT", "CREATEBOOLEANARRAY_SLOT", "CREATESTRINGARRAY_SLOT", "CREATEINSPECTABLEARRAY_SLOT", "CREATEGUIDARRAY_SLOT", "CREATEDATETIMEARRAY_SLOT", "CREATETIMESPANARRAY_SLOT", "CREATEPOINTARRAY_SLOT", "CREATESIZEARRAY_SLOT", "CREATERECTARRAY_SLOT"),
            genericInvokeSlots = listOf("CreateEmpty_0", "CreateUInt8_1", "CreateInt16_2", "CreateUInt16_3", "CreateInt32_4", "CreateUInt32_5", "CreateInt64_6", "CreateUInt64_7", "CreateSingle_8", "CreateDouble_9", "CreateChar16_10", "CreateBoolean_11", "CreateString_12", "CreateInspectable_13", "CreateGuid_14", "CreateDateTime_15", "CreateTimeSpan_16", "CreatePoint_17", "CreateSize_18", "CreateRect_19", "CreateUInt8Array_20", "CreateInt16Array_21", "CreateUInt16Array_22", "CreateInt32Array_23", "CreateUInt32Array_24", "CreateInt64Array_25", "CreateUInt64Array_26", "CreateSingleArray_27", "CreateDoubleArray_28", "CreateChar16Array_29", "CreateBooleanArray_30", "CreateStringArray_31", "CreateInspectableArray_32", "CreateGuidArray_33", "CreateDateTimeArray_34", "CreateTimeSpanArray_35", "CreatePointArray_36", "CreateSizeArray_37", "CreateRectArray_38"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IReference",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("VALUE_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IPropertyValue"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IReferenceArray",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("VALUE_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IPropertyValue"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IStringable",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("TOSTRING_SLOT"),
            genericInvokeSlots = listOf("ToString_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IUriEscapeStatics",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("UNESCAPECOMPONENT_SLOT", "ESCAPECOMPONENT_SLOT"),
            genericInvokeSlots = listOf("UnescapeComponent_0", "EscapeComponent_1"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IUriRuntimeClass",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("ABSOLUTEURI_GETTER_SLOT", "DISPLAYURI_GETTER_SLOT", "DOMAIN_GETTER_SLOT", "EXTENSION_GETTER_SLOT", "FRAGMENT_GETTER_SLOT", "HOST_GETTER_SLOT", "PASSWORD_GETTER_SLOT", "PATH_GETTER_SLOT", "QUERY_GETTER_SLOT", "QUERYPARSED_GETTER_SLOT", "RAWURI_GETTER_SLOT", "SCHEMENAME_GETTER_SLOT", "USERNAME_GETTER_SLOT", "PORT_GETTER_SLOT", "SUSPICIOUS_GETTER_SLOT", "EQUALS_SLOT", "COMBINEURI_SLOT"),
            genericInvokeSlots = listOf("Equals_0", "CombineUri_1"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IUriRuntimeClassFactory",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATEURI_SLOT", "CREATEWITHRELATIVEURI_SLOT"),
            genericInvokeSlots = listOf("CreateUri_0", "CreateWithRelativeUri_1"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IUriRuntimeClassWithAbsoluteCanonicalUri",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("ABSOLUTECANONICALURI_GETTER_SLOT", "DISPLAYIRI_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IWwwFormUrlDecoderEntry",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("NAME_GETTER_SLOT", "VALUE_GETTER_SLOT"),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IWwwFormUrlDecoderRuntimeClass",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("GETFIRSTVALUEBYNAME_SLOT"),
            genericInvokeSlots = listOf("GetFirstValueByName_0"),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.IWwwFormUrlDecoderEntry>", "Windows.Foundation.Collections.IVectorView<Windows.Foundation.IWwwFormUrlDecoderEntry>"),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.IWwwFormUrlDecoderRuntimeClassFactory",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = listOf("CREATEWWWFORMURLDECODER_SLOT"),
            genericInvokeSlots = listOf("CreateWwwFormUrlDecoder_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.MemoryBuffer",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IClosable", "Windows.Foundation.IMemoryBuffer"),
            explicitForwards = listOf("Close", "CreateReference"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Point",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.PropertyValue",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Rect",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Size",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.TimeSpan",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.TypedEventHandler",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = listOf("Invoke_0"),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.UniversalApiContract",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = emptyList(),
            explicitForwards = emptyList(),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.Uri",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IStringable", "Windows.Foundation.IUriRuntimeClass", "Windows.Foundation.IUriRuntimeClassWithAbsoluteCanonicalUri"),
            explicitForwards = listOf("CombineUri", "Equals", "ToString", "get_AbsoluteCanonicalUri", "get_AbsoluteUri", "get_DisplayIri", "get_DisplayUri", "get_Domain", "get_Extension", "get_Fragment", "get_Host", "get_Password", "get_Path", "get_Port", "get_Query", "get_QueryParsed", "get_RawUri", "get_SchemeName", "get_Suspicious", "get_UserName"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.WwwFormUrlDecoder",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.Collections.IIterable<Windows.Foundation.IWwwFormUrlDecoderEntry>", "Windows.Foundation.Collections.IVectorView<Windows.Foundation.IWwwFormUrlDecoderEntry>", "Windows.Foundation.IWwwFormUrlDecoderRuntimeClass"),
            explicitForwards = listOf("First", "GetAt", "GetFirstValueByName", "GetMany", "IndexOf", "get_Size"),
        ),
        AbiImplementationEntry(
            typeName = "Windows.Foundation.WwwFormUrlDecoderEntry",
            writesAbi = true,
            writesImplementationClass = false,
            vtableSlots = emptyList(),
            genericInvokeSlots = emptyList(),
            requiredInterfaces = listOf("Windows.Foundation.IWwwFormUrlDecoderEntry"),
            explicitForwards = listOf("get_Name", "get_Value"),
        ),
    )
    val ENTRIES_BY_TYPE_NAME: Map<String, AbiImplementationEntry> = ENTRIES.associateBy { it.typeName }

    fun entryForType(typeName: String): AbiImplementationEntry? =
        ENTRIES_BY_TYPE_NAME[typeName]

    fun requiresAbi(typeName: String): Boolean =
        entryForType(typeName)?.writesAbi == true

    fun installAbiImplementations(install: (AbiImplementationEntry) -> Unit) {
        ENTRIES.forEach(install)
    }

    fun requiredInterfaceNames(): Set<String> =
        ENTRIES.flatMap { it.requiredInterfaces }.toSet()
}
