// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT License.
package io.github.composefluent.winrt.gallery.helpers

internal class Language(val Name: String, val Code: String)
internal object LanguageList {
    val Languages: List<Language> = listOf(
        Language("English", "en"),
        Language("Arabic", "ar"),
        Language("Afrikaans", "af"),
        Language("Albanian", "sq"),
        Language("Amharic", "am"),
        Language("Armenian", "hy"),
        Language("Assamese", "as"),
        Language("Azerbaijani", "az"),
        Language("Basque ", "eu"),
        Language("Belarusian", "be"),
        Language("Bangla", "bn"),
        Language("Bosnian", "bs"),
        Language("Bulgarian", "bg"),
        Language("Catalan", "ca"),
        Language("Chinese (Simplified)", "zh"),
        Language("Croatian", "hr"),
        Language("Czech", "cs"),
        Language("Danish", "da"),
        Language("Dari", "prs"),
        Language("Dutch", "nl"),
        Language("Estonian", "et"),
        Language("Filipino", "fil"),
        Language("Finnish", "fi"),
        Language("French ", "fr"),
        Language("Galician", "gl"),
        Language("Georgian", "ka"),
        Language("German", "de"),
        Language("Greek", "el"),
        Language("Gujarati", "gu"),
        Language("Hausa", "ha"),
        Language("Hebrew", "he"),
        Language("Hindi", "hi"),
        Language("Hungarian", "hu"),
        Language("Icelandic", "is"),
        Language("Indonesian", "id"),
        Language("Irish", "ga"),
        Language("isiXhosa", "xh"),
        Language("isiZulu", "zu"),
        Language("Italian", "it"),
        Language("Japanese ", "ja"),
        Language("Kannada", "kn"),
        Language("Kazakh", "kk"),
        Language("Khmer", "km"),
        Language("Kinyarwanda", "rw"),
        Language("KiSwahili", "sw"),
        Language("Konkani", "kok"),
        Language("Korean", "ko"),
        Language("Lao", "lo"),
        Language("Latvian", "lv"),
        Language("Lithuanian", "lt"),
        Language("Luxembourgish", "lb"),
        Language("Macedonian", "mk"),
        Language("Malay", "ms"),
        Language("Malayalam", "ml"),
        Language("Maltese", "mt"),
        Language("Maori ", "mi"),
        Language("Marathi", "mr"),
        Language("Nepali", "ne"),
        Language("Norwegian", "nb"),
        Language("Odia", "or"),
        Language("Persian", "fa"),
        Language("Polish", "pl"),
        Language("Portuguese", "pt"),
        Language("Punjabi", "pa"),
        Language("Quechua", "quz"),
        Language("Romanian", "ro"),
        Language("Russian", "ru"),
        Language("Serbian (Latin)", "sr"),
        Language("Sesotho sa Leboa", "nso"),
        Language("Setswana", "tn"),
        Language("Sinhala", "si"),
        Language("Slovak ", "sk"),
        Language("Slovenian", "sl"),
        Language("Spanish", "es"),
        Language("Swedish", "sv"),
        Language("Tamil", "ta"),
        Language("Telugu", "te"),
        Language("Thai", "th"),
        Language("Tigrinya", "ti"),
        Language("Turkish", "tr"),
        Language("Ukrainian", "uk"),
        Language("Urdu", "ur"),
        Language("Uzbek (Latin)", "uz"),
        Language("Vietnamese", "vi"),
        Language("Welsh", "cy"),
        Language("Wolof", "wo")
    )
}
