package io.github.composefluent.winrt.runtime

/**
 * Marks a statically planned projection call-site declaration whose body must be generated by the
 * kotlin-winrt compiler lowering before the containing artifact is published.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
annotation class WinRTProjectionCallSite(
    val descriptor: String,
)
